name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Prepare Build Wrapper
        run: |
          echo "--> Download Build Wrapper"
          curl -o ~/build-wrapper-linux-x86.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          echo "--> Uncompress the zip"
          unzip ~/build-wrapper-linux-x86.zip -d ~/
          echo "--> Additional execution permission"
          chmod +x ~/build-wrapper-linux-x86/build-wrapper-linux-x86-64
          echo "--> Move to /usr/local/bin directory"
          sudo mv ~/build-wrapper-linux-x86/* /usr/local/bin/
          echo "--> Start"
          mkdir build
          cd build
          cmake ..
          build-wrapper-linux-x86-64 --out-dir /home/runner/work/libde265/libde265/build_wrapper_output make
          echo "/home/runner/work/libde265 ================================================================="
          ls -lh /home/runner/work/libde265
          echo "/home/runner/work/libde265/libde265 ========================================================"
          ls -lh /home/runner/work/libde265/libde265
          echo "/home/runner/work/libde265/libde265/build_wrapper_output ==================================="
          ls -lh /home/runner/work/libde265/libde265/build_wrapper_output
      
      - name: SonarCloud Scan
        run: |
          echo "/home/runner/work/libde265 ================================================================="
          ls -lh /home/runner/work/libde265
          echo "/home/runner/work/libde265/libde265 ========================================================"
          ls -lh /home/runner/work/libde265/libde265
          echo "/home/runner/work/libde265/libde265/build_wrapper_output ==================================="
          ls -lh /home/runner/work/libde265/libde265/build_wrapper_output
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
